"use client";

import { useEffect, useRef, useState } from "react";
import QRCode from "qrcode";
import bwipjs from "bwip-js/browser";
import { BrowserMultiFormatReader, BrowserQRCodeReader } from "@zxing/browser";
import { BarcodeFormat } from "@zxing/library";
import { Check, Clipboard, Download, ExternalLink, ImageUp, LoaderCircle, QrCode, ScanLine } from "lucide-react";
import { Button } from "@/components/button";

const field = "mt-2 h-11 w-full rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] px-3 text-sm";
const label = "text-sm font-semibold";

function Shell({ eyebrow, title, copy, children }: { eyebrow: string; title: string; copy: string; children: React.ReactNode }) {
  return <main className="mx-auto w-[min(1120px,calc(100%-2rem))] py-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[var(--accent-strong)]">{eyebrow}</p><h1 className="mt-3 text-4xl font-semibold md:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted">{copy}</p>{children}</main>;
}

function download(href: string, name: string) { const anchor = document.createElement("a"); anchor.href = href; anchor.download = name; anchor.click(); }
function svgUrl(svg: string) { return URL.createObjectURL(new Blob([svg], { type: "image/svg+xml" })); }

const qrTypes = ["Text", "URL", "Email", "Phone", "SMS", "Wi-Fi"] as const;

export function QrGenerator() {
  const [type, setType] = useState<(typeof qrTypes)[number]>("Text");
  const [value, setValue] = useState("Hello from Convora");
  const [extra, setExtra] = useState("");
  const [size, setSize] = useState(320);
  const [level, setLevel] = useState<"L" | "M" | "Q" | "H">("M");
  const [foreground, setForeground] = useState("#071b19");
  const [background, setBackground] = useState("#ffffff");
  const [margin, setMargin] = useState(4);
  const [png, setPng] = useState("");
  const [svg, setSvg] = useState("");
  const payload = type === "URL" ? value : type === "Email" ? `mailto:${value}` : type === "Phone" ? `tel:${value}` : type === "SMS" ? `sms:${value}${extra ? `?body=${encodeURIComponent(extra)}` : ""}` : type === "Wi-Fi" ? `WIFI:T:WPA;S:${value};P:${extra};;` : value;

  useEffect(() => { let live = true; const options = { width: size, margin, errorCorrectionLevel: level, color: { dark: foreground, light: background } }; Promise.all([QRCode.toDataURL(payload || " ", options), QRCode.toString(payload || " ", { ...options, type: "svg" })]).then(([p, s]) => { if (live) { setPng(p); setSvg(s); } }); return () => { live = false; }; }, [payload, size, level, foreground, background, margin]);

  return <Shell eyebrow="Other · QR generator" title="Make a QR code." copy="Choose the kind of content, tune its appearance and resilience, then export a crisp PNG or SVG."><div className="mt-10 grid gap-6 lg:grid-cols-[1fr_0.85fr]"><section className="rounded-[8px] p-6 glass"><div className="grid grid-cols-3 gap-2 sm:grid-cols-6">{qrTypes.map((item) => <button key={item} onClick={() => { setType(item); setValue(""); setExtra(""); }} className={`rounded-full px-3 py-2 text-xs font-semibold transition ${type === item ? "bg-[var(--accent)] text-[#041310]" : "border border-[var(--border)] bg-[var(--surface-strong)]"}`}>{item}</button>)}</div><div className="mt-6"><label className={label}>{type === "Wi-Fi" ? "Network name" : type === "SMS" ? "Phone number" : `${type} content`}</label>{type === "Text" ? <textarea value={value} onChange={(e) => setValue(e.target.value)} rows={4} className="mt-2 w-full rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-3 text-sm" /> : <input value={value} onChange={(e) => setValue(e.target.value)} placeholder={type === "URL" ? "https://example.com" : "Enter a value"} className={field} />}</div>{(type === "SMS" || type === "Wi-Fi") && <div className="mt-4"><label className={label}>{type === "Wi-Fi" ? "Password" : "Message"}</label><input value={extra} onChange={(e) => setExtra(e.target.value)} className={field} /></div>}<div className="mt-6 grid gap-5 sm:grid-cols-2"><Control label={`Size · ${size}px`}><input type="range" min="160" max="800" step="20" value={size} onChange={(e) => setSize(+e.target.value)} className="mt-4 w-full accent-[var(--accent)]" /></Control><Control label="Error correction"><select value={level} onChange={(e) => setLevel(e.target.value as typeof level)} className={field}><option value="L">Low (7%)</option><option value="M">Medium (15%)</option><option value="Q">Quartile (25%)</option><option value="H">High (30%)</option></select></Control><Control label={`Margin · ${margin}`}><input type="range" min="0" max="12" value={margin} onChange={(e) => setMargin(+e.target.value)} className="mt-4 w-full accent-[var(--accent)]" /></Control><div className="grid grid-cols-2 gap-3"><Color label="Foreground" value={foreground} set={setForeground} /><Color label="Background" value={background} set={setBackground} /></div></div></section><Preview image={png} alt="Generated QR code"><Button onClick={() => download(png, "convora-qr.png")}><Download size={17} /> PNG</Button><Button variant="secondary" onClick={() => { const url = svgUrl(svg); download(url, "convora-qr.svg"); setTimeout(() => URL.revokeObjectURL(url), 1000); }}><Download size={17} /> SVG</Button></Preview></div></Shell>;
}

const formats = [
  { name: "Code 128", bcid: "code128", sample: "CONVORA-2026" }, { name: "Code 39", bcid: "code39", sample: "CONVORA" },
  { name: "EAN-13", bcid: "ean13", sample: "5901234123457" }, { name: "EAN-8", bcid: "ean8", sample: "96385074" }, { name: "UPC-A", bcid: "upca", sample: "012345678905" },
] as const;

export function BarcodeGenerator() {
  const canvas = useRef<HTMLCanvasElement>(null); const [format, setFormat] = useState<(typeof formats)[number]>(formats[0]); const [value, setValue] = useState<string>(format.sample); const [scale, setScale] = useState(3); const [height, setHeight] = useState(18); const [showText, setShowText] = useState(true); const [error, setError] = useState("");
  useEffect(() => { if (!canvas.current) return; let message = ""; try { bwipjs.toCanvas(canvas.current, { bcid: format.bcid, text: value, scale, height, includetext: showText, textxalign: "center", backgroundcolor: "ffffff" }); } catch (reason) { message = reason instanceof Error ? reason.message : "This value is not valid for the selected format."; } queueMicrotask(() => setError(message)); }, [format, value, scale, height, showText]);
  const options = { bcid: format.bcid, text: value, scale, height, includetext: showText, textxalign: "center" as const, backgroundcolor: "ffffff" };
  return <Shell eyebrow="Other · Barcode generator" title="Build a barcode." copy="Create standards-friendly barcodes with adjustable scale and height, ready for raster or vector export."><div className="mt-10 grid gap-6 lg:grid-cols-[1fr_0.85fr]"><section className="rounded-[8px] p-6 glass"><label className={label}>Format</label><select value={format.bcid} onChange={(e) => { const next = formats.find((f) => f.bcid === e.target.value)!; setFormat(next); setValue(next.sample); }} className={field}>{formats.map((item) => <option key={item.bcid} value={item.bcid}>{item.name}</option>)}</select><div className="mt-5"><label className={label}>Value</label><input value={value} onChange={(e) => setValue(e.target.value)} className={field} /></div>{error && <p className="mt-3 text-sm text-[var(--rose)]">{error}</p>}<div className="mt-6 grid gap-5 sm:grid-cols-2"><Control label={`Scale · ${scale}x`}><input type="range" min="1" max="6" value={scale} onChange={(e) => setScale(+e.target.value)} className="mt-4 w-full accent-[var(--accent)]" /></Control><Control label={`Height · ${height}mm`}><input type="range" min="8" max="40" value={height} onChange={(e) => setHeight(+e.target.value)} className="mt-4 w-full accent-[var(--accent)]" /></Control></div><label className="mt-6 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={showText} onChange={(e) => setShowText(e.target.checked)} className="size-4 accent-[var(--accent)]" /> Show readable value</label></section><section className="flex min-h-[360px] flex-col items-center justify-center rounded-[8px] p-6 glass-strong"><div className="flex w-full flex-1 items-center justify-center overflow-auto rounded-[8px] bg-white p-6"><canvas ref={canvas} className="max-w-full" /></div><div className="mt-5 flex gap-3"><Button disabled={!!error} onClick={() => canvas.current && download(canvas.current.toDataURL("image/png"), `convora-${format.bcid}.png`)}><Download size={17} /> PNG</Button><Button disabled={!!error} variant="secondary" onClick={() => { try { const url = svgUrl(bwipjs.toSVG(options)); download(url, `convora-${format.bcid}.svg`); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch {} }}><Download size={17} /> SVG</Button></div></section></div></Shell>;
}

export function CodeScanner({ kind }: { kind: "qr" | "barcode" }) {
  const [preview, setPreview] = useState(""); const [busy, setBusy] = useState(false); const [result, setResult] = useState<{ text: string; format: string } | null>(null); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
  async function scan(file?: File) { if (!file) return; setBusy(true); setError(""); setResult(null); if (preview) URL.revokeObjectURL(preview); const url = URL.createObjectURL(file); setPreview(url); try { const reader = kind === "qr" ? new BrowserQRCodeReader() : new BrowserMultiFormatReader(); const decoded = await reader.decodeFromImageUrl(url); const format = BarcodeFormat[decoded.getBarcodeFormat()]?.replaceAll("_", " ") || (kind === "qr" ? "QR CODE" : "BARCODE"); setResult({ text: decoded.getText(), format }); } catch { setError(`No ${kind === "qr" ? "QR code" : "barcode"} could be read. Try a sharper, well-lit image with the full code visible.`); } finally { setBusy(false); } }
  const isLink = !!result && /^https?:\/\//i.test(result.text);
  return <Shell eyebrow={`Other · ${kind} scanner`} title={`Read a ${kind === "qr" ? "QR code" : "barcode"}.`} copy={`Upload an image and Convora will detect and decode the ${kind === "qr" ? "QR code" : "barcode"} locally in your browser.`}><div className="mt-10 grid gap-6 lg:grid-cols-[1fr_0.85fr]"><section className="rounded-[8px] p-6 glass"><label className="flex min-h-[310px] cursor-pointer flex-col items-center justify-center rounded-[8px] border border-dashed border-[var(--border)] bg-[var(--surface-strong)] p-8 text-center transition hover:border-[var(--accent)]">{preview ? <img src={preview} alt="Uploaded code" className="max-h-64 max-w-full object-contain" /> : <><span className="grid size-14 place-items-center rounded-full bg-[var(--accent-soft)] text-[var(--accent-strong)]">{kind === "qr" ? <QrCode /> : <ScanLine />}</span><strong className="mt-5">Choose a code image</strong><span className="mt-2 text-sm text-muted">PNG, JPG, WebP, GIF, or BMP</span></>}<input type="file" accept="image/*" className="sr-only" onChange={(e) => scan(e.target.files?.[0])} /></label></section><section className="flex min-h-[360px] flex-col justify-center rounded-[8px] p-6 glass-strong">{busy ? <div className="text-center"><LoaderCircle className="mx-auto animate-spin text-[var(--accent-strong)]" /><p className="mt-4 text-sm text-muted">Looking for a code…</p></div> : result ? <><span className="flex size-12 items-center justify-center rounded-full bg-[var(--accent-soft)] text-[var(--accent-strong)]"><Check /></span><p className="mt-6 text-xs font-semibold uppercase tracking-[0.16em] text-muted">{result.format}</p><div className="mt-3 max-h-44 overflow-auto break-all rounded-[8px] border border-[var(--border)] bg-[var(--surface)] p-4 font-mono text-sm leading-6">{result.text}</div><div className="mt-5 flex flex-wrap gap-3"><Button onClick={async () => { await navigator.clipboard.writeText(result.text); setCopied(true); setTimeout(() => setCopied(false), 1500); }}><Clipboard size={17} /> {copied ? "Copied" : "Copy"}</Button>{isLink && <Button variant="secondary" onClick={() => window.open(result.text, "_blank", "noopener,noreferrer")}><ExternalLink size={17} /> Open link</Button>}</div></> : <div className="text-center"><ImageUp className="mx-auto text-muted" size={34} /><p className="mt-4 font-semibold">Your decoded result will appear here.</p>{error && <p className="mt-3 text-sm leading-6 text-[var(--rose)]">{error}</p>}</div>}</section></div></Shell>;
}

function Control({ label: text, children }: { label: string; children: React.ReactNode }) { return <div><p className={label}>{text}</p>{children}</div>; }
function Color({ label: text, value, set }: { label: string; value: string; set: (value: string) => void }) { return <label className="text-xs font-semibold text-muted">{text}<input type="color" value={value} onChange={(e) => set(e.target.value)} className="mt-2 h-10 w-full cursor-pointer rounded-[8px] border border-[var(--border)] bg-transparent p-1" /></label>; }
function Preview({ image, alt, children }: { image: string; alt: string; children: React.ReactNode }) { return <section className="flex min-h-[460px] flex-col items-center justify-center rounded-[8px] p-6 glass-strong"><div className="flex flex-1 items-center justify-center">{image && <img src={image} alt={alt} className="max-h-[340px] max-w-full rounded-[8px]" />}</div><div className="mt-5 flex gap-3">{children}</div></section>; }
