"use client";

import { useMemo, useState } from "react";
import { Download, FileText, GripVertical, LoaderCircle, Replace, Scissors, Upload, X } from "lucide-react";
import JSZip from "jszip";
import { Button } from "@/components/button";
import { formatBytes } from "@/lib/utils";
import { docxWithXml, documentPages, documentSections, keepBodyRanges, mergeDocx, openDocx, replaceDocumentText, type DocumentSection } from "./document-ooxml";

export type AdvancedDocumentKind = "images" | "replace" | "merge" | "split" | "sections" | "counter";
type ExtractedImage = { name: string; blob: Blob; url: string; width?: number; height?: number; format: string };
const acceptDocx = ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document";
const info: Record<AdvancedDocumentKind, [string, string, string]> = {
  images: ["Documents · Extract images", "Recover every image inside a document.", "Preview embedded DOCX media and download originals individually or together."],
  replace: ["Documents · Find & replace", "Update repeated text without rebuilding the document.", "Replace text across DOCX paragraphs while retaining the surrounding document structure and styling."],
  merge: ["Documents · Merge", "Bring Word documents into one ordered file.", "Arrange multiple DOCX files and merge them using Word's embedded-document format for strong fidelity."],
  split: ["Documents · Split", "Split a Word document by page ranges.", "See the detected page count, define ranges such as 1–4 and 5–8, then download separate DOCX files."],
  sections: ["Documents · Extract sections", "Keep only the parts you need.", "Select heading-defined sections and create a new DOCX in their original order."],
  counter: ["Documents · Word counter", "Measure a document at a glance.", "Count words, characters, sentences, paragraphs, and estimated reading or speaking time."],
};

export function AdvancedDocumentWorkspace({ kind }: { kind: AdvancedDocumentKind }) {
  const [eyebrow, title, description] = info[kind];
  return <main className="mx-auto w-[min(1120px,calc(100%-2rem))] py-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[var(--accent-strong)]">{eyebrow}</p><h1 className="mt-3 max-w-4xl text-4xl font-semibold md:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted">{description}</p><div className="mt-10">{kind === "images" ? <ExtractImages /> : kind === "replace" ? <FindReplace /> : kind === "merge" ? <Merge /> : kind === "split" ? <PageSplit /> : kind === "sections" ? <SectionTool /> : <Counter />}</div></main>;
}

function Dropzone({ accept = acceptDocx, multiple, label, onFiles }: { accept?: string; multiple?: boolean; label: string; onFiles: (files: File[]) => void }) { return <label className="flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-[8px] border border-dashed border-[var(--border)] bg-[var(--surface-strong)] p-6 text-center transition hover:border-[var(--accent)]"><Upload className="text-[var(--accent-strong)]" /><strong className="mt-4">{label}</strong><span className="mt-2 text-sm text-muted">Processed locally for this session</span><input type="file" className="sr-only" accept={accept} multiple={multiple} onChange={(e) => { onFiles(Array.from(e.target.files ?? [])); e.target.value = ""; }} /></label>; }
function Shell({ children }: { children: React.ReactNode }) { return <section className="rounded-[8px] p-6 glass md:p-8">{children}</section>; }
function ErrorText({ value }: { value: string }) { return value ? <p className="mt-4 rounded-[8px] bg-[color-mix(in_srgb,var(--rose)_12%,transparent)] p-3 text-sm text-[var(--rose)]">{value}</p> : null; }
function save(blob: BlobPart, name: string, type = "application/octet-stream") { const url = URL.createObjectURL(new Blob([blob], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function stem(name: string) { return name.replace(/\.[^.]+$/, ""); }
async function dimensions(blob: Blob) { try { const bitmap = await createImageBitmap(blob); const value = { width: bitmap.width, height: bitmap.height }; bitmap.close(); return value; } catch { return {}; } }

async function extractImages(file: File) {
  const zip = await JSZip.loadAsync(await file.arrayBuffer()); const results: ExtractedImage[] = [];
  for (const entry of Object.values(zip.files).filter((item) => !item.dir && /^word\/media\//i.test(item.name))) {
    const blob = await entry.async("blob"); const format = entry.name.split(".").pop()?.toUpperCase() ?? "FILE"; const size = await dimensions(blob);
    results.push({ name: entry.name.split("/").pop()!, blob, url: URL.createObjectURL(blob), format, ...size });
  }
  return results;
}
function ExtractImages() {
  const [file, setFile] = useState<File | null>(null), [images, setImages] = useState<ExtractedImage[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function load(next: File) { setFile(next); setBusy(true); images.forEach((image) => URL.revokeObjectURL(image.url)); try { const found = await extractImages(next); setImages(found); setError(found.length ? "" : "No embedded images were found in this document."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not inspect this document."); } finally { setBusy(false); } }
  async function all() { const zip = new JSZip(); images.forEach((image) => zip.file(image.name, image.blob)); save(await zip.generateAsync({ type: "blob" }), `${stem(file!.name)}-images.zip`, "application/zip"); }
  return <Shell><Dropzone label="Choose a DOCX file" onFiles={(files) => files[0] && load(files[0])} />{busy && <Status text="Finding embedded images…" />}<ErrorText value={error} />{images.length > 0 && <><div className="mt-5 flex items-center justify-between"><p className="text-sm font-semibold">{images.length} image{images.length === 1 ? "" : "s"} found</p><Button onClick={all}><Download size={17} /> Download all ZIP</Button></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{images.map((image) => <article key={image.name} className="overflow-hidden rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)]"><div className="grid h-44 place-items-center bg-white/70 p-3"><img src={image.url} alt={image.name} className="max-h-full max-w-full object-contain" /></div><div className="p-4"><p className="truncate text-sm font-semibold">{image.name}</p><p className="mt-1 text-xs text-muted">{image.format} · {image.width ? `${image.width} × ${image.height} · ` : ""}{formatBytes(image.blob.size)}</p><Button variant="secondary" className="mt-4 w-full" onClick={() => save(image.blob, image.name, image.blob.type)}><Download size={16} /> Download</Button></div></article>)}</div></>}</Shell>;
}

function FindReplace() {
  const [file, setFile] = useState<File | null>(null), [search, setSearch] = useState(""), [replacement, setReplacement] = useState(""), [caseSensitive, setCase] = useState(false), [wholeWord, setWhole] = useState(false), [matches, setMatches] = useState<number | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function process(download = false) { if (!file || !search) return; setBusy(true); try { const { zip, xml } = await openDocx(file); const result = replaceDocumentText(xml, search, replacement, caseSensitive, wholeWord); setMatches(result.count); if (download && result.count) save(await docxWithXml(zip, result.xml), `${stem(file.name)}-updated.docx`, file.type); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not update this document."); } finally { setBusy(false); } }
  return <Shell><Dropzone label={file?.name ?? "Choose a DOCX file"} onFiles={(files) => { setFile(files[0]); setMatches(null); }} /><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Find" value={search} onChange={(value) => { setSearch(value); setMatches(null); }} /><Field label="Replace with" value={replacement} onChange={setReplacement} /></div><div className="mt-4 flex flex-wrap gap-5 text-sm font-semibold"><Toggle label="Case sensitive" checked={caseSensitive} onChange={setCase} /><Toggle label="Whole words only" checked={wholeWord} onChange={setWhole} /></div><div className="mt-5 flex flex-wrap items-center gap-3"><Button variant="secondary" disabled={!file || !search || busy} onClick={() => process()}><Replace size={17} /> Count matches</Button><Button disabled={!file || !search || busy} onClick={() => process(true)}><Download size={17} /> Replace all & download</Button>{matches !== null && <span className="text-sm font-semibold text-[var(--accent-strong)]">{matches} match{matches === 1 ? "" : "es"}</span>}</div><p className="mt-4 text-xs leading-5 text-muted">Text spanning styled runs keeps the first run’s formatting. Surrounding layout, images, tables, and styles remain intact.</p><ErrorText value={error} /></Shell>;
}

function Merge() {
  const [files, setFiles] = useState<File[]>([]), [drag, setDrag] = useState<number | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState("");
  function reorder(target: number) { if (drag === null || drag === target) return; setFiles((current) => { const next = [...current]; const [item] = next.splice(drag, 1); next.splice(target, 0, item); return next; }); setDrag(null); }
  async function run() { setBusy(true); try { save(await mergeDocx(files), "merged-documents.docx", files[0].type); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not merge these files."); } finally { setBusy(false); } }
  return <Shell><Dropzone multiple label="Choose two or more DOCX files" onFiles={(next) => setFiles((current) => [...current, ...next])} /><div className="mt-5 space-y-2">{files.map((file, index) => <div key={`${file.name}-${index}`} draggable onDragStart={() => setDrag(index)} onDragOver={(e) => e.preventDefault()} onDrop={() => reorder(index)} className="flex cursor-grab items-center gap-3 rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-3"><GripVertical size={18} className="text-muted" /><span className="grid size-7 place-items-center rounded-full bg-[var(--accent-soft)] text-xs font-semibold">{index + 1}</span><FileText size={18} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{file.name}</p><p className="text-xs text-muted">{formatBytes(file.size)}</p></div><button aria-label={`Remove ${file.name}`} onClick={() => setFiles((items) => items.filter((_, i) => i !== index))}><X size={17} /></button></div>)}</div><Button className="mt-5" disabled={files.length < 2 || busy} onClick={run}>{busy ? <LoaderCircle className="animate-spin" size={17} /> : <Download size={17} />}{busy ? "Merging documents…" : "Merge & download"}</Button><p className="mt-3 text-xs text-muted">The result uses DOCX embedded-document parts. Microsoft Word resolves these on open, preserving each source document with high fidelity.</p><ErrorText value={error} /></Shell>;
}

function PageSplit() {
  type Range = { id: string; from: number; to: number };
  const [file, setFile] = useState<File | null>(null), [xml, setXml] = useState(""), [pageData, setPageData] = useState<ReturnType<typeof documentPages> | null>(null), [ranges, setRanges] = useState<Range[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function load(next: File) { setBusy(true); try { const opened = await openDocx(next); const detected = documentPages(opened.xml, opened.savedPages); setFile(next); setXml(opened.xml); setPageData(detected); setRanges([{ id: crypto.randomUUID(), from: 1, to: detected.pages.length }]); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not determine document pages."); } finally { setBusy(false); } }
  function update(id: string, key: "from" | "to", value: number) { setRanges((items) => items.map((range) => range.id === id ? { ...range, [key]: value } : range)); }
  function valid(range: Range) { return pageData && range.from >= 1 && range.to >= range.from && range.to <= pageData.pages.length; }
  async function make(range: Range) { const source = await JSZip.loadAsync(await file!.arrayBuffer()); const pages = pageData!.pages.slice(range.from - 1, range.to); return docxWithXml(source, keepBodyRanges(xml, pages)); }
  async function downloadRange(range: Range, index: number) { if (!valid(range)) return; save(await make(range), `${stem(file!.name)}-part-${index + 1}-pages-${range.from}-${range.to}.docx`, file!.type); }
  async function downloadAll() { setBusy(true); try { const output = new JSZip(); for (let index = 0; index < ranges.length; index++) if (valid(ranges[index])) output.file(`part-${index + 1}-pages-${ranges[index].from}-${ranges[index].to}.docx`, await make(ranges[index])); save(await output.generateAsync({ type: "blob" }), `${stem(file!.name)}-split.zip`, "application/zip"); } finally { setBusy(false); } }
  return <Shell><Dropzone label="Choose a DOCX file" onFiles={(files) => files[0] && load(files[0])} />{busy && <Status text="Reading document pagination…" />}<ErrorText value={error} />{pageData && <><div className="mt-5 rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-4"><p className="text-2xl font-semibold">{pageData.pages.length} page{pageData.pages.length === 1 ? "" : "s"}</p><p className="mt-1 text-xs leading-5 text-muted">{pageData.source === "breaks" ? "Based on page-break information saved in the DOCX." : pageData.source === "saved-count" ? "Page count saved by Word; range boundaries are estimated because DOCX does not store fixed page boundaries." : "Estimated from document flow because this DOCX has no saved pagination. Word may paginate it differently depending on fonts and layout."}</p></div><div className="mt-5 space-y-3">{ranges.map((range, index) => <div key={range.id} className="grid items-end gap-3 rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-4 sm:grid-cols-[auto_1fr_1fr_auto_auto]"><span className="pb-3 text-sm font-semibold">Range {index + 1}</span><NumberField label="From page" value={range.from} max={pageData.pages.length} onChange={(value) => update(range.id, "from", value)} /><NumberField label="To page" value={range.to} max={pageData.pages.length} onChange={(value) => update(range.id, "to", value)} /><Button variant="secondary" disabled={!valid(range)} onClick={() => downloadRange(range, index)}><Download size={16} /> Download</Button><button className="mb-2 grid size-9 place-items-center rounded-full hover:bg-[var(--accent-soft)]" aria-label={`Remove range ${index + 1}`} disabled={ranges.length === 1} onClick={() => setRanges((items) => items.filter((item) => item.id !== range.id))}><X size={17} /></button>{!valid(range) && <p className="text-xs text-[var(--rose)] sm:col-span-5">Enter a valid range between 1 and {pageData.pages.length}.</p>}</div>)}</div><button className="mt-4 text-sm font-semibold text-[var(--accent-strong)]" onClick={() => { const previous = ranges.at(-1); const from = Math.min(pageData.pages.length, (previous?.to ?? 0) + 1); setRanges((items) => [...items, { id: crypto.randomUUID(), from, to: pageData.pages.length }]); }}>+ Add another range</button><div className="mt-5"><Button disabled={busy || !ranges.some(valid)} onClick={downloadAll}><Scissors size={17} /> Download all ranges as ZIP</Button></div><div className="mt-6"><h2 className="text-sm font-semibold">Page preview</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{pageData.pages.map((page) => <div key={page.page} className="rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-3"><p className="text-xs font-semibold text-[var(--accent-strong)]">Page {page.page}</p><p className="mt-2 line-clamp-3 text-xs leading-5 text-muted">{page.preview || "No preview text on this page."}</p></div>)}</div></div></>}</Shell>;
}

function SectionTool() {
  const [file, setFile] = useState<File | null>(null), [sections, setSections] = useState<DocumentSection[]>([]), [selected, setSelected] = useState<string[]>([]), [zip, setZip] = useState<JSZip | null>(null), [xml, setXml] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function load(next: File) { setBusy(true); try { const opened = await openDocx(next); const found = documentSections(opened.xml); setFile(next); setZip(opened.zip); setXml(opened.xml); setSections(found); setSelected(found.map((item) => item.id)); setError(found.length === 1 && found[0].title === "Entire document" ? "No Word heading styles were found; the document is shown as one section." : ""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not read sections."); } finally { setBusy(false); } }
  async function extract() { const chosen = sections.filter((item) => selected.includes(item.id)); save(await docxWithXml(zip!, keepBodyRanges(xml, chosen)), `${stem(file!.name)}-selected.docx`, file!.type); }
  return <Shell><Dropzone label="Choose a DOCX with heading styles" onFiles={(files) => files[0] && load(files[0])} />{busy && <Status text="Reading document structure…" />}<ErrorText value={error} />{sections.length > 0 && <><div className="mt-5 space-y-2">{sections.map((section, index) => <label key={section.id} className="flex items-start gap-3 rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-4"><input type="checkbox" className="mt-1" checked={selected.includes(section.id)} onChange={() => setSelected((items) => items.includes(section.id) ? items.filter((id) => id !== section.id) : [...items, section.id])} /><span className="grid size-7 shrink-0 place-items-center rounded-full bg-[var(--accent-soft)] text-xs font-semibold">{index + 1}</span><div className="min-w-0 flex-1"><p className="font-semibold" style={{ marginLeft: `${(section.level - 1) * 12}px` }}>{section.title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted">{section.preview || "No preview text"}</p></div></label>)}</div><Button className="mt-5" disabled={!selected.length} onClick={extract}><Download size={17} /> Extract selected sections</Button></>}</Shell>;
}
function Counter() {
  const [text, setText] = useState(""); const stats = useMemo(() => countText(text), [text]);
  async function load(file: File) { if (/\.docx$/i.test(file.name)) { const mammoth = await import("mammoth/mammoth.browser"); setText((await mammoth.extractRawText({ arrayBuffer: await file.arrayBuffer() })).value); } else { const raw = await file.text(); setText(/\.rtf$/i.test(file.name) ? raw.replace(/\\par[d]?/g, "\n").replace(/\\'[0-9a-fA-F]{2}|\\[a-z]+-?\d* ?|[{}]/g, "") : raw); } }
  return <Shell><Dropzone accept=".docx,.txt,.md,.rtf,text/plain" label="Choose a DOCX, TXT, Markdown, or RTF file" onFiles={(files) => files[0] && load(files[0])} /><div className="my-5 flex items-center gap-3 text-xs font-semibold uppercase tracking-wider text-muted"><span className="h-px flex-1 bg-[var(--border)]" />or paste text<span className="h-px flex-1 bg-[var(--border)]" /></div><textarea rows={11} value={text} onChange={(e) => setText(e.target.value)} placeholder="Paste or type text here…" className="w-full rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-4 leading-6" /><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4">{stats.cards.map(([label, value]) => <div key={label} className="rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-4"><p className="text-xs text-muted">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div>{stats.frequent.length > 0 && <div className="mt-5 rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-4"><h2 className="text-sm font-semibold">Most frequent words</h2><div className="mt-3 flex flex-wrap gap-2">{stats.frequent.map(([word, amount]) => <span key={word} className="rounded-full bg-[var(--accent-soft)] px-3 py-1 text-xs font-semibold">{word} · {amount}</span>)}</div></div>}</Shell>;
}
function countText(text: string) { const words = text.trim().match(/[\p{L}\p{N}'’-]+/gu) ?? []; const sentences = text.trim() ? (text.match(/[.!?]+(?=\s|$)/g)?.length || 1) : 0; const paragraphs = text.trim() ? text.trim().split(/\n\s*\n|\n/).filter((item) => item.trim()).length : 0; const frequent = new Map<string, number>(); words.forEach((word) => { const key = word.toLowerCase(); if (key.length > 2) frequent.set(key, (frequent.get(key) ?? 0) + 1); }); return { cards: [["Words", words.length.toLocaleString()], ["Characters", text.length.toLocaleString()], ["Without spaces", text.replace(/\s/g, "").length.toLocaleString()], ["Sentences", sentences.toLocaleString()], ["Paragraphs", paragraphs.toLocaleString()], ["Reading time", `${Math.max(1, Math.ceil(words.length / 200))} min`], ["Speaking time", `${Math.max(1, Math.ceil(words.length / 130))} min`]] as Array<[string, string]>, frequent: [...frequent.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10) }; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-sm font-semibold">{label}<input value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 h-11 w-full rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] px-3 font-normal" /></label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-2"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /> {label}</label>; }
function NumberField({ label, value, max, onChange }: { label: string; value: number; max: number; onChange: (value: number) => void }) { return <label className="text-xs font-semibold">{label}<input type="number" min="1" max={max} value={value} onChange={(e) => onChange(Number(e.target.value))} className="mt-2 h-10 w-full rounded-[8px] border border-[var(--border)] bg-[var(--surface)] px-3 text-sm" /></label>; }
function Status({ text }: { text: string }) { return <p className="mt-4 flex items-center gap-2 text-sm text-muted"><LoaderCircle className="animate-spin" size={17} /> {text}</p>; }
