"use client";

import { Download, FileAudio2, FileVideo, Pause, Play, Scissors, UploadCloud, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/button";
import { audioFormats, type AudioFormatId } from "@/formats/audio-formats";
import { acceptedVideoExtensions, videoFormats, type VideoFormatId } from "@/formats/video-formats";
import { formatBytes } from "@/lib/utils";

type Mode = "convert" | "compress" | "trim" | "audio";
type VideoItem = { file: File; url: string; duration: number; width: number; height: number };
type Result = { url: string; filename: string; size: number; originalSize: number };
const accept = acceptedVideoExtensions.map((value) => `.${value}`).join(",");
const copy = {
  convert: ["Video Converter", "A new format, without the fuss.", "Choose a useful output format, resolution, quality, and frame rate. We handle the encoding details."],
  compress: ["Video Compressor", "Keep the picture. Lose the weight.", "Pick a simple quality target, then see exactly how much space your new video saves."],
  trim: ["Video Trimmer", "Keep the scene. Cut the rest.", "Set the start and end on a familiar timeline, preview your selection, and export it."],
  audio: ["Video to Audio", "Take the sound with you.", "Extract a video's audio track as MP3, WAV, AAC, M4A, or FLAC."],
} satisfies Record<Mode, string[]>;

export function VideoToolWorkspace({ mode }: { mode: Mode }) {
  const [item, setItem] = useState<VideoItem | null>(null); const [format, setFormat] = useState<VideoFormatId>("mp4");
  const [audioFormat, setAudioFormat] = useState<AudioFormatId>("mp3"); const [quality, setQuality] = useState<"small" | "balanced" | "high">("balanced");
  const [resolution, setResolution] = useState("original"); const [fps, setFps] = useState(0); const [start, setStart] = useState(0); const [end, setEnd] = useState(0);
  const [status, setStatus] = useState(""); const [error, setError] = useState(""); const [result, setResult] = useState<Result | null>(null); const [playing, setPlaying] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null); const itemRef = useRef<VideoItem | null>(null); const resultRef = useRef<Result | null>(null);
  useEffect(() => { itemRef.current = item; }, [item]); useEffect(() => { resultRef.current = result; }, [result]);
  useEffect(() => () => { if (itemRef.current) URL.revokeObjectURL(itemRef.current.url); if (resultRef.current) URL.revokeObjectURL(resultRef.current.url); }, []);

  async function addFile(file: File) { setError(""); setResult(null); try { if (file.size > 500 * 1024 * 1024) throw new Error("Video must be 500 MB or smaller."); const next = await readVideo(file); if (item) URL.revokeObjectURL(item.url); setItem(next); setStart(0); setEnd(next.duration); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to read this video."); } }
  function preview() { const video = videoRef.current; if (!video) return; if (playing) { video.pause(); setPlaying(false); return; } video.currentTime = start; video.play(); setPlaying(true); }
  function onTimeUpdate() { const video = videoRef.current; if (video && video.currentTime >= end) { video.pause(); setPlaying(false); } }
  async function process() { if (!item) return; setStatus(mode === "audio" ? "Extracting audio…" : mode === "trim" ? "Cutting selection…" : mode === "compress" ? "Compressing video…" : "Converting video…"); setError(""); const data = new FormData(); data.set("file", item.file); data.set("operation", mode); data.set("format", mode === "compress" ? "mp4" : format); data.set("audioFormat", audioFormat); data.set("quality", quality); data.set("resolution", resolution); data.set("fps", String(fps)); data.set("start", String(start)); data.set("end", String(end)); try { const response = await fetch("/api/video/process", { method: "POST", body: data }); if (!response.ok) { const payload = await response.json(); throw new Error(payload.error ?? "Video processing failed."); } const blob = await response.blob(); if (result) URL.revokeObjectURL(result.url); setResult({ url: URL.createObjectURL(blob), filename: response.headers.get("X-Convora-Filename") ?? `convora-output.${mode === "audio" ? audioFormat : format}`, size: blob.size, originalSize: item.file.size }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Video processing failed."); } finally { setStatus(""); } }
  const [eyebrow, title, description] = copy[mode]; const savings = result ? Math.round((1 - result.size / result.originalSize) * 100) : 0;
  return <main className="mx-auto w-[min(1120px,calc(100%-2rem))] py-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[var(--accent-strong)]">{eyebrow}</p><h1 className="mt-3 max-w-4xl text-4xl font-semibold md:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted">{description}</p>
    <div className="mt-10 grid gap-6 lg:grid-cols-[0.72fr_1.28fr]"><aside className="grid content-start gap-5 rounded-[8px] p-5 glass-strong">
      {mode === "audio" ? <Select label="Audio format" value={audioFormat} onChange={(value) => setAudioFormat(value as AudioFormatId)} options={Object.entries(audioFormats).filter(([id]) => ["mp3", "wav", "aac", "m4a", "flac"].includes(id)).map(([id, value]) => [id, value.label])} /> : mode !== "compress" && <Select label="Output format" value={format} onChange={(value) => setFormat(value as VideoFormatId)} options={Object.entries(videoFormats).map(([id, value]) => [id, value.label])} />}
      {mode !== "audio" && mode !== "trim" && <><div><p className="mb-2 text-sm font-semibold">Quality</p><div className="grid grid-cols-3 gap-2">{([['small','Smaller'],['balanced','Balanced'],['high','High']] as const).map(([id, label]) => <button key={id} onClick={() => setQuality(id)} className={quality === id ? "rounded-[7px] bg-[var(--accent)] px-2 py-3 text-xs font-bold text-[#041310]" : "rounded-[7px] border border-[var(--border)] px-2 py-3 text-xs font-semibold"}>{label}</button>)}</div></div><Select label="Resolution" value={resolution} onChange={setResolution} options={[["original","Original"],["1080","1080p"],["720","720p"],["480","480p"]]} /><Select label="Frame rate" value={String(fps)} onChange={(value) => setFps(Number(value))} options={[["0","Keep original"],["24","24 FPS"],["30","30 FPS"],["60","60 FPS"]]} /></>}
      <Button onClick={process} disabled={!item || Boolean(status)}>{mode === "audio" ? <FileAudio2 size={17} /> : mode === "trim" ? <Scissors size={17} /> : <FileVideo size={17} />}{status || ({ convert: "Convert video", compress: "Compress video", trim: "Export selection", audio: "Extract audio" }[mode])}</Button>
      {result && <><a href={result.url} download={result.filename} className="inline-flex h-11 items-center justify-center gap-2 rounded-full border border-[var(--border)] bg-[var(--surface-strong)] px-5 text-sm font-semibold"><Download size={17} />Download · {formatBytes(result.size)}</a><div className="grid grid-cols-3 gap-2 text-center"><Metric label="Original" value={formatBytes(result.originalSize)} /><Metric label="Output" value={formatBytes(result.size)} /><Metric label="Saved" value={savings > 0 ? `${savings}%` : "—"} accent={savings > 0} /></div></>}
      {error && <p className="rounded-[8px] bg-red-500/10 p-3 text-sm text-red-600 dark:text-red-300">{error}</p>}<p className="text-xs leading-5 text-muted">Files are processed for this request only and are not kept in a library.</p>
    </aside><section>{!item ? <Upload onFile={addFile} /> : <article className="rounded-[8px] border border-[var(--border)] bg-[var(--surface)] p-4"><div className="mb-4 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[var(--accent-soft)] text-[var(--accent-strong)]"><FileVideo size={18} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.file.name}</p><p className="text-xs text-muted">{formatBytes(item.file.size)} · {time(item.duration)} · {item.width}×{item.height}</p></div><button onClick={() => { URL.revokeObjectURL(item.url); setItem(null); setResult(null); }} className="grid size-9 place-items-center rounded-full hover:bg-[var(--accent-soft)]" aria-label="Remove video"><X size={16} /></button></div><video ref={videoRef} src={item.url} onTimeUpdate={onTimeUpdate} onPause={() => setPlaying(false)} className="aspect-video w-full rounded-[7px] bg-black object-contain" controls={mode !== "trim"} />{mode === "trim" && <><div className="mt-4 flex items-center gap-3"><button onClick={preview} className="grid size-10 shrink-0 place-items-center rounded-full bg-[var(--accent-soft)]" aria-label={playing ? "Pause preview" : "Preview selection"}>{playing ? <Pause size={16} /> : <Play size={16} />}</button><div className="relative flex-1"><div className="h-2 rounded-full bg-[var(--accent-soft)]" /><input aria-label="Trim start" type="range" min="0" max={item.duration} step="0.1" value={start} onChange={(e) => setStart(Math.min(Number(e.target.value), end - .1))} className="absolute inset-x-0 -top-2 w-full" /></div></div><div className="mt-3 grid grid-cols-2 gap-3"><TimeInput label="Start" value={start} max={end - .1} onChange={setStart} /><TimeInput label="End" value={end} min={start + .1} max={item.duration} onChange={setEnd} /></div><p className="mt-3 text-center text-sm font-semibold text-[var(--accent-strong)]">Selection · {time(Math.max(0, end - start))}</p></>}</article>}</section></div>
  </main>;
}
function Upload({ onFile }: { onFile: (file: File) => void }) { return <div onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); if (e.dataTransfer.files[0]) onFile(e.dataTransfer.files[0]); }} className="relative grid min-h-72 place-items-center rounded-[8px] border border-dashed border-[var(--border)] bg-[var(--surface)] p-6 text-center"><input id="video-upload" type="file" accept={accept} className="absolute size-px opacity-0" onChange={(e) => { if (e.target.files?.[0]) onFile(e.target.files[0]); e.target.value = ""; }} /><label htmlFor="video-upload" className="cursor-pointer"><UploadCloud size={38} className="mx-auto text-[var(--accent-strong)]" /><h2 className="mt-4 text-xl font-semibold">Add a video</h2><p className="mt-2 text-sm text-muted">Drop a file here or browse MP4, WebM, MOV, AVI, and MKV up to 500 MB.</p><span className="button-primary mt-5 inline-flex h-10 items-center rounded-full px-5 text-sm font-semibold">Browse files</span></label></div>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] | readonly (readonly string[])[] }) { return <label className="grid gap-2 text-sm font-semibold">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="h-11 rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] px-3">{options.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>; }
function Metric({ label, value, accent }: { label: string; value: string; accent?: boolean }) { return <div className="rounded-[7px] bg-[var(--accent-soft)] p-2"><p className="text-[10px] uppercase tracking-wide text-muted">{label}</p><p className={accent ? "mt-1 text-sm font-bold text-[var(--accent-strong)]" : "mt-1 text-sm font-semibold"}>{value}</p></div>; }
function TimeInput({ label, value, min = 0, max, onChange }: { label: string; value: number; min?: number; max: number; onChange: (value: number) => void }) { return <label className="grid gap-1 text-xs font-semibold text-muted">{label}<input type="number" min={min} max={max} step="0.1" value={value.toFixed(1)} onChange={(e) => onChange(Math.min(max, Math.max(min, Number(e.target.value))))} className="h-10 rounded-[7px] border border-[var(--border)] bg-[var(--surface-strong)] px-3 text-sm text-[var(--foreground)]" /></label>; }
function time(seconds: number) { const minutes = Math.floor(seconds / 60); return `${minutes}:${String(Math.floor(seconds % 60)).padStart(2, "0")}`; }
function readVideo(file: File) { return new Promise<VideoItem>((resolve, reject) => { const url = URL.createObjectURL(file); const video = document.createElement("video"); video.preload = "metadata"; video.src = url; video.onloadedmetadata = () => resolve({ file, url, duration: video.duration, width: video.videoWidth, height: video.videoHeight }); video.onerror = () => { URL.revokeObjectURL(url); reject(new Error("This video could not be previewed. Try MP4, WebM, MOV, AVI, or MKV.")); }; }); }
