"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, Clipboard, Download, Eye, EyeOff, FileCheck2, LoaderCircle, LockKeyhole, RefreshCw, ShieldCheck, Upload, X } from "lucide-react";
import { Button } from "@/components/button";
import { decryptWithPassword, encryptFileData, generatePassword, hashFileData, normalizeHash } from "./security-utils";

type Kind = "encrypt" | "decrypt" | "hash" | "password";
const inputClass = "mt-2 h-11 w-full rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] px-3 text-sm";
const copy = {
  encrypt: ["Security · Encrypt file", "Put a password around any file.", "AES-256-GCM encryption runs on this device. The encrypted download includes its original filename and tamper protection."],
  decrypt: ["Security · Decrypt file", "Bring your protected file back.", "Choose a .convora file and enter its password. The original file is restored locally after its integrity is verified."],
  hash: ["Security · File hash & checksum", "Give every file a fingerprint.", "Generate a SHA checksum, or compare the result with one supplied by a publisher or collaborator."],
  password: ["Security · Password generator", "Make strong passwords without sharing them.", "Generate passwords with secure browser randomness and controls for length and character types."],
} as const;

export function SecurityToolWorkspace({ kind }: { kind: Kind }) {
  const meta = copy[kind];
  return <main className="mx-auto w-[min(1120px,calc(100%-2rem))] py-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[var(--accent-strong)]">{meta[0]}</p><h1 className="mt-3 max-w-4xl text-4xl font-semibold md:text-6xl">{meta[1]}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted">{meta[2]}</p><div className="mt-10">{kind === "encrypt" ? <CryptoFile mode="encrypt" /> : kind === "decrypt" ? <CryptoFile mode="decrypt" /> : kind === "hash" ? <HashTool /> : <PasswordTool />}</div></main>;
}

function download(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function Dropzone({ file, accept, onFile }: { file: File | null; accept?: string; onFile: (file: File | null) => void }) { return file ? <div className="flex items-center gap-4 rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-4"><FileCheck2 className="text-[var(--accent-strong)]" /><div className="min-w-0 flex-1"><p className="truncate font-semibold">{file.name}</p><p className="text-xs text-muted">{formatBytes(file.size)}</p></div><button aria-label="Remove file" onClick={() => onFile(null)}><X size={19} /></button></div> : <label className="flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-[8px] border border-dashed border-[var(--border)] bg-[var(--surface-strong)] p-7 text-center transition hover:border-[var(--accent)]"><Upload className="text-[var(--accent-strong)]" /><strong className="mt-4">Choose a file</strong><span className="mt-2 text-sm text-muted">Processed only in this browser</span><input type="file" accept={accept} className="sr-only" onChange={(event) => onFile(event.target.files?.[0] ?? null)} /></label>; }
function formatBytes(value: number) { if (!value) return "0 B"; const unit = Math.floor(Math.log(value) / Math.log(1024)); return `${(value / 1024 ** unit).toFixed(unit ? 1 : 0)} ${["B", "KB", "MB", "GB"][unit]}`; }

function CryptoFile({ mode }: { mode: "encrypt" | "decrypt" }) {
  const [file, setFile] = useState<File | null>(null); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function process() { if (!file || !password) return; if (mode === "encrypt" && password !== confirm) { setError("The passwords do not match."); return; } if (mode === "encrypt" && password.length < 8) { setError("Use at least 8 characters for the password."); return; } setBusy(true); setError(""); try { if (mode === "encrypt") { const result = await encryptFileData(await file.arrayBuffer(), password, file.name); download(result, `${file.name}.convora`); } else { const result = await decryptWithPassword(await file.arrayBuffer(), password); download(new Blob([result.data]), result.filename); } } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not process this file."); } finally { setBusy(false); } }
  return <Panel><Dropzone file={file} accept={mode === "decrypt" ? ".convora,application/vnd.convora.encrypted" : undefined} onFile={(next) => { setFile(next); setError(""); }} /><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className="text-sm font-semibold">Password</label><div className="relative"><input type={show ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} className={`${inputClass} pr-11`} autoComplete="new-password" /><button type="button" aria-label={show ? "Hide password" : "Show password"} className="absolute right-3 top-5 text-muted" onClick={() => setShow(!show)}>{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></div>{mode === "encrypt" && <div><label className="text-sm font-semibold">Confirm password</label><input type={show ? "text" : "password"} value={confirm} onChange={(e) => setConfirm(e.target.value)} className={inputClass} autoComplete="new-password" /></div>}</div>{mode === "encrypt" && <p className="mt-3 text-xs leading-5 text-muted">Convora cannot recover this password. Store it somewhere safe.</p>}{error && <ErrorAlert text={error} />}<Button className="mt-5" disabled={!file || !password || busy} onClick={process}>{busy ? <LoaderCircle className="animate-spin" size={17} /> : <LockKeyhole size={17} />} {busy ? "Working…" : mode === "encrypt" ? "Encrypt & download" : "Decrypt & download"}</Button></Panel>;
}

function HashTool() {
  const [file, setFile] = useState<File | null>(null); const [algorithm, setAlgorithm] = useState<"SHA-256" | "SHA-384" | "SHA-512">("SHA-256"); const [hash, setHash] = useState(""); const [expected, setExpected] = useState(""); const [busy, setBusy] = useState(false); const matches = expected ? normalizeHash(expected) === hash : null;
  useEffect(() => { setHash(""); }, [file, algorithm]);
  async function calculate() { if (!file) return; setBusy(true); try { setHash(await hashFileData(await file.arrayBuffer(), algorithm)); } finally { setBusy(false); } }
  return <Panel><Dropzone file={file} onFile={setFile} /><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className="text-sm font-semibold">Algorithm</label><select className={inputClass} value={algorithm} onChange={(e) => setAlgorithm(e.target.value as typeof algorithm)}><option>SHA-256</option><option>SHA-384</option><option>SHA-512</option></select></div><div><label className="text-sm font-semibold">Expected checksum <span className="font-normal text-muted">(optional)</span></label><input className={`${inputClass} font-mono`} value={expected} onChange={(e) => setExpected(e.target.value)} placeholder="Paste checksum to verify" /></div></div><Button className="mt-5" disabled={!file || busy} onClick={calculate}>{busy ? <LoaderCircle className="animate-spin" size={17} /> : <ShieldCheck size={17} />} Calculate checksum</Button>{hash && <div className="mt-5 rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-muted">{algorithm}</p><CopyButton value={hash} /></div><p className="mt-3 break-all font-mono text-sm leading-6">{hash}</p>{matches !== null && <p className={`mt-3 flex items-center gap-2 text-sm font-semibold ${matches ? "text-[var(--accent-strong)]" : "text-[var(--rose)]"}`}>{matches ? <Check size={17} /> : <X size={17} />}{matches ? "Checksum matches" : "Checksum does not match"}</p>}</div>}</Panel>;
}

const sets = { Uppercase: "ABCDEFGHIJKLMNOPQRSTUVWXYZ", Lowercase: "abcdefghijklmnopqrstuvwxyz", Numbers: "0123456789", Symbols: "!@#$%^&*()-_=+[]{};:,.?" };
function PasswordTool() {
  const [length, setLength] = useState(20); const [enabled, setEnabled] = useState(Object.keys(sets)); const [password, setPassword] = useState(""); const selected = useMemo(() => enabled.map((key) => sets[key as keyof typeof sets]), [enabled]);
  function regenerate() { try { setPassword(generatePassword(length, selected)); } catch { setPassword(""); } }
  useEffect(() => { regenerate(); }, [length, enabled]); // eslint-disable-line react-hooks/exhaustive-deps
  const entropy = selected.length ? Math.floor(length * Math.log2(selected.join("").length)) : 0;
  return <Panel><div className="rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-4"><div className="flex gap-3"><input aria-label="Generated password" readOnly value={password} className="min-w-0 flex-1 bg-transparent font-mono text-lg font-semibold outline-none" /><CopyButton value={password} /></div></div><div className="mt-6"><div className="flex items-center justify-between"><label className="text-sm font-semibold">Length</label><strong>{length}</strong></div><input type="range" min="8" max="64" value={length} onChange={(e) => setLength(Number(e.target.value))} className="mt-3 w-full accent-[var(--accent)]" /></div><fieldset className="mt-6"><legend className="text-sm font-semibold">Character types</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{Object.keys(sets).map((key) => <label key={key} className="flex cursor-pointer items-center gap-3 rounded-[8px] border border-[var(--border)] bg-[var(--surface-strong)] p-3 text-sm"><input type="checkbox" checked={enabled.includes(key)} onChange={() => setEnabled((items) => items.includes(key) ? items.filter((item) => item !== key) : [...items, key])} className="size-4 accent-[var(--accent)]" />{key}</label>)}</div></fieldset><div className="mt-5 flex flex-wrap items-center gap-4"><Button disabled={!selected.length} onClick={regenerate}><RefreshCw size={17} /> Generate another</Button><span className="text-sm text-muted">Estimated entropy: <strong className="text-[var(--foreground)]">{entropy} bits</strong></span></div></Panel>;
}

function CopyButton({ value }: { value: string }) { const [copied, setCopied] = useState(false); return <button type="button" disabled={!value} className="inline-flex shrink-0 items-center gap-2 text-sm font-semibold text-[var(--accent-strong)] disabled:opacity-40" onClick={async () => { await navigator.clipboard.writeText(value); setCopied(true); setTimeout(() => setCopied(false), 1500); }}>{copied ? <Check size={17} /> : <Clipboard size={17} />}{copied ? "Copied" : "Copy"}</button>; }
function Panel({ children }: { children: React.ReactNode }) { return <section className="rounded-[8px] p-6 glass md:p-8">{children}</section>; }
function ErrorAlert({ text }: { text: string }) { return <p className="mt-4 rounded-[8px] bg-[color-mix(in_srgb,var(--rose)_12%,transparent)] p-3 text-sm text-[var(--rose)]">{text}</p>; }
